In [17]:
#creating an array
import numpy as np

In [18]:
a = np.array([2, 4, 6, 8, 10])

In [19]:
print(a)

[ 2  4  6  8 10]


In [5]:
#creating an array using arange()
a = np.arange(1, 11)

In [6]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#creating an array all zeros
p = np.zeros((3,3))

In [8]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#creating an array all ones
q = np.ones((2,2))

In [10]:
print(q)

[[1. 1.]
 [1. 1.]]


In [11]:
#creating a constant array
r = np.full((2, 2), 4)

In [12]:
print(r)

[[4 4]
 [4 4]]


In [13]:
#creating 2x2 identity matrix
s = np.eye(4)

In [14]:
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# creating an array 3x3 with random values
t = np.random.random((3,3))

In [16]:
print(t)

[[0.0632263  0.52749999 0.0529323 ]
 [0.04769048 0.89104068 0.1347266 ]
 [0.03394921 0.33342801 0.0435269 ]]


In [20]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
print(a.dtype)

int32


In [22]:
print(a.shape)

(5,)


In [24]:
#selecting an array elements
a = np.array([[4, 3],[2, 1]])

In [25]:
print(a)

[[4 3]
 [2 1]]


In [26]:
print([1,0])

[1, 0]


In [27]:
print(a[1,0])

2


In [28]:
print(a[0,0])

4


In [29]:
print(a[0,1])

3


In [30]:
print(a[1,0])

2


In [31]:
print(a[1,1])

1


In [32]:
#imaginary number
c = complex(33, 3)

In [33]:
print(c)

(33+3j)


In [34]:
#dtype objects
a = np.array([2, 4, 6, 8, 10])

In [36]:
print(a.dtype)

int32


In [37]:
print(a.dtype.itemsize)

4
