In [17]:
#creating an array
import numpy as np

In [18]:
a = np.array([2, 4, 6, 8, 10])

In [19]:
print(a)

[ 2  4  6  8 10]


In [5]:
a = np.arange(1, 11)

In [6]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
p = np.zeros((3,3))

In [8]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
q = np.ones((2,2))

In [10]:
print(q)

[[1. 1.]
 [1. 1.]]


In [11]:
r = np.full((2, 2), 4)

In [12]:
print(r)

[[4 4]
 [4 4]]


In [13]:
s = np.eye(4)

In [14]:
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
t = np.random.random((3,3))

In [16]:
print(t)

[[0.0632263  0.52749999 0.0529323 ]
 [0.04769048 0.89104068 0.1347266 ]
 [0.03394921 0.33342801 0.0435269 ]]
