In [1]:
# import genfromtxt function
from numpy import genfromtxt

# read comma separated file
product_data = genfromtxt('demo.csv', delimiter=',')

# display initial 5 records
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [3]:
# import numpy
import numpy as np

# create a sample array
sample_array = np.asarray([[1,2,3], [4,5,6], [7,8,9]])

# write sample array to CSV file
np.savetxt("my_first_demo.csv", sample_array, delimiter=",")

In [4]:
# import pandas 
import pandas as pd

# read CSV file
sample_df = pd.read_csv('demo.csv', sep=',', header=None)

# display initial 5 records
sample_df.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

In [5]:
# check my_first_demo.csv
check_first_demo = pd.read_csv('my_first_demo.csv', sep=',', header=None)

# display initial 5 records - in this case all array
check_first_demo.head()

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0

In [6]:
# save DataFrame to CSV file
sample_df.to_csv('demo_sample_df.csv')

In [7]:
# check what you have saved
check_saved = pd.read_csv('demo_sample_df.csv', sep=',', header=None)

# display initial 5 records - data overwrited (in this case doesn't matter)
check_saved.head()

0   1   2   3
0  NaN   0   1   2
1  0.0  14  32  33
2  1.0  24  45  26
3  2.0  27  38  39